# Generated by Django 5.2.10 on 2026-01-30 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forestcompartment",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available for Lease"),
                    ("pending", "Pending Approval"),
                    ("leased", "Leased"),
                    ("protected", "Protected / Reserve"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeaseContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("annual_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "is_signed_eri",
                    models.BooleanField(
                        default=False, help_text="ERI bilan imzolangan"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "contract_pdf",
                    models.FileField(blank=True, null=True, upload_to="contracts/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compartment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="core.forestcompartment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.JSONField(help_text="GIS Point (JSON format)")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
